
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      # Set the timezone to your local timezone
      - TZ=Europe/Madrid
      - BASIC_AUTH_USERNAME=     #set your own
      - BASIC_AUTH_PASSWORD=     #set your own
    ports:
      - '8945:8945'
    volumes:
      - /YOUR/PREFERED/PATH/.config:/config   #change
      - /YOUR/DOWNLOADS:/downloads  #change
